apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whereami-ingress
  labels:
    app: whereami
spec:
  rules:
  - host: whereami.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: whereami-service
            port:
              number: 80